version: '3'

tasks:

  omni:
    desc: Create or Delete an omni cluster
    cmds:
    -  eval "$(teller sh)" && go run .

  lint:
    desc: Lint the code
    cmds:
    - golint ./...
    - yamlfmt .
    - yamllint . --strict
